/* AUTO-GENERATED by scripts/generate-roles.mjs — DO NOT EDIT MANUALLY */
export const ROLE_IDS = [
  "admin",
  "anr",
  "client",
  "composer",
  "engineer",
  "guest",
  "owner",
  "producer",
  "publisher",
] as const;

export type UserRole = typeof ROLE_IDS[number];

export const ROLE_LABEL: Record<UserRole, string> = {
  "admin": "Admin",
  "anr": "A&R",
  "client": "Client",
  "composer": "Composer",
  "engineer": "Audio Engineer",
  "guest": "Guest",
  "owner": "Owner",
  "producer": "Producer",
  "publisher": "Publisher",
};

// Adjust jika kamu punya kolom/aturan admin-like sendiri.
export const isAdminLike = (r: UserRole | null | undefined): boolean =>
  r === "owner" || r === "admin";
