-- Music Genre Database
-- Table structure for music genres and sub-genres
-- Based on comprehensive list of music types

CREATE TABLE IF NOT EXISTS music_genres (
    id SERIAL PRIMARY KEY,
    genre VARCHAR(100) NOT NULL,
    sub_genre VARCHAR(150) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create index for faster queries
CREATE INDEX idx_genre ON music_genres(genre);
CREATE INDEX idx_sub_genre ON music_genres(sub_genre);

-- Insert music genres and sub-genres
INSERT INTO music_genres (genre, sub_genre) VALUES

-- Alternative
('Alternative', 'Art Punk'),
('Alternative', 'Alternative Rock'),
('Alternative', 'Britpunk'),
('Alternative', 'College Rock'),
('Alternative', 'Crossover Thrash'),
('Alternative', 'Crust Punk'),
('Alternative', 'Emotional Hardcore (emo / emocore)'),
('Alternative', 'Experimental Rock'),
('Alternative', 'Folk Punk'),
('Alternative', 'Goth / Gothic Rock'),
('Alternative', 'Grunge'),
('Alternative', 'Hardcore Punk'),
('Alternative', 'Hard Rock'),
('Alternative', 'Indie Rock'),
('Alternative', 'Lo-fi'),
('Alternative', 'Musique Concrète'),
('Alternative', 'New Wave'),
('Alternative', 'Progressive Rock'),
('Alternative', 'Punk'),
('Alternative', 'Shoegaze'),
('Alternative', 'Steampunk'),

-- Anime
('Anime', 'Anime'),

-- Blues
('Blues', 'Acoustic Blues'),
('Blues', 'African Blues'),
('Blues', 'Blues Rock'),
('Blues', 'Blues Shouter'),
('Blues', 'British Blues'),
('Blues', 'Canadian Blues'),
('Blues', 'Chicago Blues'),
('Blues', 'Classic Blues'),
('Blues', 'Classic Female Blues'),
('Blues', 'Contemporary Blues'),
('Blues', 'Contemporary R&B'),
('Blues', 'Country Blues'),
('Blues', 'Dark Blues'),
('Blues', 'Delta Blues'),
('Blues', 'Detroit Blues'),
('Blues', 'Doom Blues'),
('Blues', 'Electric Blues'),
('Blues', 'Folk Blues'),
('Blues', 'Gospel Blues'),
('Blues', 'Harmonica Blues'),
('Blues', 'Hill Country Blues'),
('Blues', 'Hokum Blues'),
('Blues', 'Jazz Blues'),
('Blues', 'Jump Blues'),
('Blues', 'Kansas City Blues'),
('Blues', 'Louisiana Blues'),
('Blues', 'Memphis Blues'),
('Blues', 'Modern Blues'),
('Blues', 'New Orlean Blues'),
('Blues', 'NY Blues'),
('Blues', 'Piano Blues'),
('Blues', 'Piedmont Blues'),
('Blues', 'Punk Blues'),
('Blues', 'Ragtime Blues'),
('Blues', 'Rhythm Blues'),
('Blues', 'Soul Blues'),
('Blues', 'St. Louis Blues'),
('Blues', 'Swamp Blues'),
('Blues', 'Texas Blues'),
('Blues', 'Urban Blues'),
('Blues', 'Vandeville'),
('Blues', 'West Coast Blues'),
('Blues', 'Zydeco'),

-- Children's Music
('Children''s Music', 'Lullabies'),
('Children''s Music', 'Sing-Along'),
('Children''s Music', 'Stories'),

-- Classical
('Classical', 'Avant-Garde'),
('Classical', 'Ballet'),
('Classical', 'Baroque'),
('Classical', 'Cantata'),
('Classical', 'Chamber Music'),
('Classical', 'String Quartet'),
('Classical', 'Chant'),
('Classical', 'Choral'),
('Classical', 'Classical Crossover'),
('Classical', 'Concerto'),
('Classical', 'Concerto Grosso'),
('Classical', 'Contemporary Classical'),
('Classical', 'Early Music'),
('Classical', 'Expressionist'),
('Classical', 'High Classical'),
('Classical', 'Impressionist'),
('Classical', 'Mass Requiem'),
('Classical', 'Medieval'),
('Classical', 'Minimalism'),
('Classical', 'Modern Composition'),
('Classical', 'Modern Classical'),
('Classical', 'Opera'),
('Classical', 'Oratorio'),
('Classical', 'Orchestral'),
('Classical', 'Organum'),
('Classical', 'Renaissance'),
('Classical', 'Romantic (early period)'),
('Classical', 'Romantic (later period)'),
('Classical', 'Sonata'),
('Classical', 'Symphonic'),
('Classical', 'Symphony'),
('Classical', 'Twelve-tone'),
('Classical', 'Wedding Music'),

-- Comedy
('Comedy', 'Novelty'),
('Comedy', 'Parody Music'),
('Comedy', 'Stand-up Comedy'),
('Comedy', 'Vaudeville'),

-- Commercial
('Commercial', 'Jingles'),
('Commercial', 'TV Themes'),

-- Country
('Country', 'Alternative Country'),
('Country', 'Americana'),
('Country', 'Australian Country'),
('Country', 'Bakersfield Sound'),
('Country', 'Bluegrass'),
('Country', 'Progressive Bluegrass'),
('Country', 'Reactionary Bluegrass'),
('Country', 'Blues Country'),
('Country', 'Cajun Fiddle Tunes'),
('Country', 'Christian Country'),
('Country', 'Classic Country'),
('Country', 'Close Harmony'),
('Country', 'Contemporary Bluegrass'),
('Country', 'Contemporary Country'),
('Country', 'Country Gospel'),
('Country', 'Country Pop'),
('Country', 'Country Rap'),
('Country', 'Country Rock'),
('Country', 'Country Soul'),
('Country', 'Cowboy / Western'),
('Country', 'Cowpunk'),
('Country', 'Dansband'),
('Country', 'Honky Tonk'),
('Country', 'Franco-Country'),
('Country', 'Gulf and Western'),
('Country', 'Hellbilly Music'),
('Country', 'Instrumental Country'),
('Country', 'Lubbock Sound'),
('Country', 'Nashville Sound'),
('Country', 'Neotraditional Country'),
('Country', 'Outlaw Country'),
('Country', 'Progressive'),
('Country', 'Psychobilly / Punkabilly'),
('Country', 'Red Dirt'),
('Country', 'Sertanejo'),
('Country', 'Texas County'),
('Country', 'Traditional Bluegrass'),
('Country', 'Traditional Country'),
('Country', 'Truck-Driving Country'),
('Country', 'Urban Cowboy'),
('Country', 'Western Swing'),
('Country', 'Zydeco'),

-- Dance
('Dance', 'Club / Club Dance'),
('Dance', 'Breakcore'),
('Dance', 'Breakbeat / Breakstep'),
('Dance', '4-Beat'),
('Dance', 'Acid Breaks'),
('Dance', 'Baltimore Club'),
('Dance', 'Big Beat'),
('Dance', 'Breakbeat Hardcore'),
('Dance', 'Broken Beat'),
('Dance', 'Florida Breaks'),
('Dance', 'Nu Skool Breaks'),
('Dance', 'Brostep'),
('Dance', 'Chillstep'),
('Dance', 'Deep House'),
('Dance', 'Dubstep'),
('Dance', 'Electro House'),
('Dance', 'Electroswing'),
('Dance', 'Exercise'),
('Dance', 'Future Garage'),
('Dance', 'Garage'),
('Dance', 'Glitch Hop'),
('Dance', 'Glitch Pop'),
('Dance', 'Grime'),
('Dance', 'Hardcore'),
('Dance', 'Bouncy House'),
('Dance', 'Bouncy Techno'),
('Dance', 'Digital Hardcore'),
('Dance', 'Doomcore'),
('Dance', 'Dubstyle'),
('Dance', 'Gabber'),
('Dance', 'Happy Hardcore'),
('Dance', 'Hardstyle'),
('Dance', 'Jumpstyle'),
('Dance', 'Makina'),
('Dance', 'Speedcore'),
('Dance', 'Terrorcore'),
('Dance', 'Uk Hardcore'),
('Dance', 'Hard Dance'),
('Dance', 'Hi-NRG / Eurodance'),
('Dance', 'Horrorcore'),
('Dance', 'House'),
('Dance', 'Acid House'),
('Dance', 'Chicago House'),
('Dance', 'Diva House'),
('Dance', 'Dutch House'),
('Dance', 'Freestyle House'),
('Dance', 'French House'),
('Dance', 'Funky House'),
('Dance', 'Ghetto House'),
('Dance', 'Hardbag'),
('Dance', 'Hip House'),
('Dance', 'Italo House'),
('Dance', 'Latin House'),
('Dance', 'Minimal House'),
('Dance', 'Progressive House'),
('Dance', 'Rave Music'),
('Dance', 'Swing House'),
('Dance', 'Tech House'),
('Dance', 'Tribal House'),
('Dance', 'Tropical House'),
('Dance', 'UK Hard House'),
('Dance', 'US Garage'),
('Dance', 'Vocal House'),
('Dance', 'Jackin House'),
('Dance', 'Jungle / Drum''n''bass'),
('Dance', 'Liquid Dub'),
('Dance', 'Regstep'),
('Dance', 'Speedcore'),
('Dance', 'Techno'),
('Dance', 'Acid Techno'),
('Dance', 'Detroit Techno'),
('Dance', 'Free Tekno'),
('Dance', 'Ghettotech'),
('Dance', 'Minimal'),
('Dance', 'Nortec'),
('Dance', 'Schranz'),
('Dance', 'Techno-Dnb'),
('Dance', 'Technopop'),
('Dance', 'Tecno Brega'),
('Dance', 'Toytown Techno'),
('Dance', 'Trance'),
('Dance', 'Acid Trance'),
('Dance', 'Acid-House'),
('Dance', 'Classic Trance'),
('Dance', 'Dark Psy'),
('Dance', 'Dream Trance'),
('Dance', 'Goa Trance'),
('Dance', 'Dark Psytrance'),
('Dance', 'Full on'),
('Dance', 'Psybreaks'),
('Dance', 'Psyprog'),
('Dance', 'Suomisaundi'),
('Dance', 'Hard Trance'),
('Dance', 'Prog. Trance'),
('Dance', 'Psy-Trance'),
('Dance', 'Minimal Techno'),
('Dance', 'Tech Trance'),
('Dance', 'Uplifting Trance'),
('Dance', 'Orchestral Uplifting'),
('Dance', 'Vocal Trance'),
('Dance', 'Trap'),

-- Disney
('Disney', 'Disney'),

-- Easy Listening
('Easy Listening', 'Background'),
('Easy Listening', 'Bop'),
('Easy Listening', 'Elevator'),
('Easy Listening', 'Furniture'),
('Easy Listening', 'Lounge'),
('Easy Listening', 'Middle of the Road'),
('Easy Listening', 'Swing'),

-- Electronic
('Electronic', '2-Step'),
('Electronic', '8bit'),
('Electronic', 'Ambient'),
('Electronic', 'Ambient Dub'),
('Electronic', 'Ambient House'),
('Electronic', 'Ambient Techno'),
('Electronic', 'Dark Ambient'),
('Electronic', 'Drone Music'),
('Electronic', 'Illbient'),
('Electronic', 'Isolationism'),
('Electronic', 'Lowercase'),
('Electronic', 'Asian Underground'),
('Electronic', 'Bassline'),
('Electronic', 'Chillwave'),
('Electronic', 'Chiptune'),
('Electronic', 'Bitpop'),
('Electronic', 'Game Boy'),
('Electronic', 'Nintendocore'),
('Electronic', 'Video Game Music'),
('Electronic', 'Yorkshire Bleeps and Bass'),
('Electronic', 'Crunk'),
('Electronic', 'Downtempo'),
('Electronic', 'Acid Jazz'),
('Electronic', 'Balearic Beat'),
('Electronic', 'Chill Out'),
('Electronic', 'Dub Music'),
('Electronic', 'Dubtronica'),
('Electronic', 'Ethnic Electronica'),
('Electronic', 'Moombahton'),
('Electronic', 'Nu Jazz'),
('Electronic', 'Trip Hop'),
('Electronic', 'Drum & Bass'),
('Electronic', 'Darkcore'),
('Electronic', 'Darkstep'),
('Electronic', 'Drumfunk'),
('Electronic', 'Drumstep'),
('Electronic', 'Hardstep'),
('Electronic', 'Intelligent Drum and Bass'),
('Electronic', 'Jump-Up'),
('Electronic', 'Liquid Funk'),
('Electronic', 'Neurofunk'),
('Electronic', 'Oldschool Jungle'),
('Electronic', 'Darkside Jungle'),
('Electronic', 'Ragga Jungle'),
('Electronic', 'Raggacore'),
('Electronic', 'Sambass'),
('Electronic', 'Techstep'),
('Electronic', 'Electro'),
('Electronic', 'Electro Backbeat'),
('Electronic', 'Electro-Grime'),
('Electronic', 'Electropop'),
('Electronic', 'Electro-swing'),
('Electronic', 'Electroacoustic'),
('Electronic', 'Acousmatic Music'),
('Electronic', 'Computer Music'),
('Electronic', 'Electroacoustic Improvisation'),
('Electronic', 'Field Recording'),
('Electronic', 'Live Coding'),
('Electronic', 'Live Electronics'),
('Electronic', 'Soundscape Composition'),
('Electronic', 'Tape Music'),
('Electronic', 'Electronica'),
('Electronic', 'Berlin School'),
('Electronic', 'Electronic Art Music'),
('Electronic', 'Electronic Dance Music'),
('Electronic', 'Folktronica'),
('Electronic', 'Freestyle Music'),
('Electronic', 'Glitch'),
('Electronic', 'Idm'),
('Electronic', 'Laptronica'),
('Electronic', 'Skweee'),
('Electronic', 'Sound Art'),
('Electronic', 'Synthcore'),
('Electronic', 'Electronic Rock'),
('Electronic', 'Alternative Dance'),
('Electronic', 'Baggy'),
('Electronic', 'Madchester'),
('Electronic', 'Dance-Punk'),
('Electronic', 'Dance-Rock'),
('Electronic', 'Dark Wave'),
('Electronic', 'Electroclash'),
('Electronic', 'Electronicore'),
('Electronic', 'Electropunk'),
('Electronic', 'Ethereal Wave'),
('Electronic', 'Indietronica'),
('Electronic', 'New Rave'),
('Electronic', 'Space Rock'),
('Electronic', 'Synthpop'),
('Electronic', 'Synthpunk'),
('Electronic', 'Eurodance'),
('Electronic', 'Bubblegum Dance'),
('Electronic', 'Italo Dance'),
('Electronic', 'Turbofolk'),
('Electronic', 'Hardstyle'),
('Electronic', 'Hi-Nrg'),
('Electronic', 'Eurobeat'),
('Electronic', 'Hard Nrg'),
('Electronic', 'New Beat'),
('Electronic', 'IDM/Experimental'),
('Electronic', 'Industrial'),
('Electronic', 'Vaporwave'),
('Electronic', 'Hyponagogic'),
('Electronic', 'Vektroid'),
('Electronic', 'Mallsoft'),
('Electronic', 'Vaportrap'),
('Electronic', 'Vaporhop'),
('Electronic', 'Protovapor'),
('Electronic', 'UK Garage'),
('Electronic', '2-Step'),
('Electronic', '4×4'),
('Electronic', 'Speed Garage'),

-- Enka
('Enka', 'Enka'),

-- French Pop
('French Pop', 'French Pop'),

-- Folk Music
('Folk Music', 'American Folk Revival'),
('Folk Music', 'Anti-Folk'),
('Folk Music', 'British Folk Revival'),
('Folk Music', 'Contemporary Folk'),
('Folk Music', 'Filk Music'),
('Folk Music', 'Freak Folk'),
('Folk Music', 'Indie Folk'),
('Folk Music', 'Industrial Folk'),
('Folk Music', 'Neofolk'),
('Folk Music', 'Progressive Folk'),
('Folk Music', 'Psychedelic Folk'),
('Folk Music', 'Sung Poetry'),
('Folk Music', 'Techno-Folk'),

-- German Folk
('German Folk', 'German Folk'),

-- German Pop
('German Pop', 'German Pop'),

-- Fitness & Workout
('Fitness & Workout', 'Fitness & Workout'),

-- Hip-Hop/Rap
('Hip-Hop/Rap', 'Alternative Rap'),
('Hip-Hop/Rap', 'Avant-Garde'),
('Hip-Hop/Rap', 'Bounce'),
('Hip-Hop/Rap', 'Chap Hop'),
('Hip-Hop/Rap', 'Christian Hip Hop'),
('Hip-Hop/Rap', 'Conscious Hip Hop'),
('Hip-Hop/Rap', 'Country-Rap'),
('Hip-Hop/Rap', 'Grunk'),
('Hip-Hop/Rap', 'Crunkcore'),
('Hip-Hop/Rap', 'Cumbia Rap'),
('Hip-Hop/Rap', 'Dirty South'),
('Hip-Hop/Rap', 'East Coast'),
('Hip-Hop/Rap', 'Brick City Club'),
('Hip-Hop/Rap', 'Hardcore Hip Hop'),
('Hip-Hop/Rap', 'Mafioso Rap'),
('Hip-Hop/Rap', 'New Jersey Hip Hop'),
('Hip-Hop/Rap', 'Freestyle Rap'),
('Hip-Hop/Rap', 'G-Funk'),
('Hip-Hop/Rap', 'Gangsta Rap'),
('Hip-Hop/Rap', 'Golden Age'),
('Hip-Hop/Rap', 'Grime'),
('Hip-Hop/Rap', 'Hardcore Rap'),
('Hip-Hop/Rap', 'Hip-Hop'),
('Hip-Hop/Rap', 'Hip Pop'),
('Hip-Hop/Rap', 'Horrorcore'),
('Hip-Hop/Rap', 'Hyphy'),
('Hip-Hop/Rap', 'Industrial Hip Hop'),
('Hip-Hop/Rap', 'Instrumental Hip Hop'),
('Hip-Hop/Rap', 'Jazz Rap'),
('Hip-Hop/Rap', 'Latin Rap'),
('Hip-Hop/Rap', 'Low Bap'),
('Hip-Hop/Rap', 'Lyrical Hip Hop'),
('Hip-Hop/Rap', 'Merenrap'),
('Hip-Hop/Rap', 'Midwest Hip Hop'),
('Hip-Hop/Rap', 'Chicago Hip Hop'),
('Hip-Hop/Rap', 'Detroit Hip Hop'),
('Hip-Hop/Rap', 'St. Louis Hip Hop'),
('Hip-Hop/Rap', 'Twin Cities Hip Hop'),
('Hip-Hop/Rap', 'Motswako'),
('Hip-Hop/Rap', 'Nerdcore'),
('Hip-Hop/Rap', 'New Jack Swing'),
('Hip-Hop/Rap', 'New School Hip Hop'),
('Hip-Hop/Rap', 'Old School Rap'),
('Hip-Hop/Rap', 'Rap'),
('Hip-Hop/Rap', 'Trap'),
('Hip-Hop/Rap', 'Turntablism'),
('Hip-Hop/Rap', 'Underground Rap'),
('Hip-Hop/Rap', 'West Coast Rap'),

-- Holiday
('Holiday', 'Chanukah'),
('Holiday', 'Christmas'),
('Holiday', 'Christmas: Children''s'),
('Holiday', 'Christmas: Classic'),
('Holiday', 'Christmas: Classical'),
('Holiday', 'Christmas: Comedy'),
('Holiday', 'Christmas: Jazz'),
('Holiday', 'Christmas: Modern'),
('Holiday', 'Christmas: Pop'),
('Holiday', 'Christmas: R&B'),
('Holiday', 'Christmas: Religious'),
('Holiday', 'Christmas: Rock'),
('Holiday', 'Easter'),
('Holiday', 'Halloween'),
('Holiday', 'Holiday: Other'),
('Holiday', 'Thanksgiving'),

-- Indie Pop
('Indie Pop', 'Indie Pop'),

-- Industrial
('Industrial', 'Aggrotech'),
('Industrial', 'Coldwave'),
('Industrial', 'Cybergrind'),
('Industrial', 'Dark Electro'),
('Industrial', 'Death Industrial'),
('Industrial', 'Electro-Industrial'),
('Industrial', 'Electronic Body Music'),
('Industrial', 'Futurepop'),
('Industrial', 'Industrial Metal'),
('Industrial', 'Neue Deutsche Härte'),
('Industrial', 'Industrial Rock'),
('Industrial', 'Noise'),
('Industrial', 'Japanoise'),
('Industrial', 'Power Electronics'),
('Industrial', 'Power Noise'),
('Industrial', 'Witch House'),

-- Inspirational – Christian & Gospel
('Inspirational', 'CCM'),
('Inspirational', 'Christian Metal'),
('Inspirational', 'Christian Pop'),
('Inspirational', 'Christian Rap'),
('Inspirational', 'Christian Rock'),
('Inspirational', 'Classic Christian'),
('Inspirational', 'Contemporary Gospel'),
('Inspirational', 'Gospel'),
('Inspirational', 'Christian & Gospel'),
('Inspirational', 'Praise & Worship'),
('Inspirational', 'Qawwali'),
('Inspirational', 'Southern Gospel'),
('Inspirational', 'Traditional Gospel'),

-- Instrumental
('Instrumental', 'March'),

-- J-Pop
('J-Pop', 'J-Pop'),
('J-Pop', 'J-Rock'),
('J-Pop', 'J-Synth'),
('J-Pop', 'J-Ska'),
('J-Pop', 'J-Punk'),

-- Jazz
('Jazz', 'Acid Jazz'),
('Jazz', 'Afro-Cuban Jazz'),
('Jazz', 'Avant-Garde Jazz'),
('Jazz', 'Bebop'),
('Jazz', 'Big Band'),
('Jazz', 'Blue Note'),
('Jazz', 'British Dance Band'),
('Jazz', 'Cape Jazz'),
('Jazz', 'Chamber Jazz'),
('Jazz', 'Contemporary Jazz'),
('Jazz', 'Continental Jazz'),
('Jazz', 'Cool Jazz'),
('Jazz', 'Crossover Jazz'),
('Jazz', 'Dark Jazz'),
('Jazz', 'Dixieland'),
('Jazz', 'Early Jazz'),
('Jazz', 'Electro Swing'),
('Jazz', 'Ethio-jazz'),
('Jazz', 'Ethno-Jazz'),
('Jazz', 'European Free Jazz'),
('Jazz', 'Free Funk'),
('Jazz', 'Free Jazz'),
('Jazz', 'Fusion'),
('Jazz', 'Gypsy Jazz'),
('Jazz', 'Hard Bop'),
('Jazz', 'Indo Jazz'),
('Jazz', 'Jazz Blues'),
('Jazz', 'Jazz-Funk'),
('Jazz', 'Jazz-Fusion'),
('Jazz', 'Jazz Rap'),
('Jazz', 'Jazz Rock'),
('Jazz', 'Kansas City Jazz'),
('Jazz', 'Latin Jazz'),
('Jazz', 'M-Base Jazz'),
('Jazz', 'Mainstream Jazz'),
('Jazz', 'Modal Jazz'),
('Jazz', 'Neo-Bop'),
('Jazz', 'Neo-Swing'),
('Jazz', 'Nu Jazz'),
('Jazz', 'Orchestral Jazz'),
('Jazz', 'Post-Bop'),
('Jazz', 'Punk Jazz'),
('Jazz', 'Ragtime'),
('Jazz', 'Ska Jazz'),
('Jazz', 'Skiffle'),
('Jazz', 'Smooth Jazz'),
('Jazz', 'Soul Jazz'),
('Jazz', 'Swing Jazz'),
('Jazz', 'Straight-Ahead Jazz'),
('Jazz', 'Trad Jazz'),
('Jazz', 'Third Stream'),
('Jazz', 'West Coast Jazz'),

-- K-Pop
('K-Pop', 'K-Pop'),

-- Karaoke
('Karaoke', 'Karaoke'),

-- Kayokyoku
('Kayokyoku', 'Kayokyoku'),

-- Latin
('Latin', 'Alternativo & Rock Latino'),
('Latin', 'Argentine Tango'),
('Latin', 'Bachata'),
('Latin', 'Baithak Gana'),
('Latin', 'Baladas y Boleros'),
('Latin', 'Bolero'),
('Latin', 'Bossa Nova'),
('Latin', 'Brazilian'),
('Latin', 'Axé'),
('Latin', 'Brazilian Rock'),
('Latin', 'Brega'),
('Latin', 'Choro'),
('Latin', 'Forró'),
('Latin', 'Frevo'),
('Latin', 'Funk Carioca'),
('Latin', 'Lambada'),
('Latin', 'Maracatu'),
('Latin', 'Música Popular Brasileira'),
('Latin', 'Música Sertaneja'),
('Latin', 'Pagode'),
('Latin', 'Samba'),
('Latin', 'Samba Rock'),
('Latin', 'Tecnobrega'),
('Latin', 'Tropicalia'),
('Latin', 'Zouk-Lambada'),
('Latin', 'Chicha'),
('Latin', 'Criolla'),
('Latin', 'Contemporary Latin'),
('Latin', 'Cumbia'),
('Latin', 'Flamenco / Spanish Flamenco'),
('Latin', 'Huayno'),
('Latin', 'Joropo'),
('Latin', 'Latin Jazz'),
('Latin', 'Mambo'),
('Latin', 'Mariachi'),
('Latin', 'Merengue Típico'),
('Latin', 'Nuevo Flamenco'),
('Latin', 'Pop Latino'),
('Latin', 'Portuguese Fado'),
('Latin', 'Punta'),
('Latin', 'Punta Rock'),
('Latin', 'Ranchera'),
('Latin', 'Raíces'),
('Latin', 'Raison'),
('Latin', 'Reggaeton y Hip-Hop'),
('Latin', 'Regional Mexicano'),
('Latin', 'Salsa y Tropical'),
('Latin', 'Soca'),
('Latin', 'Son'),
('Latin', 'Tejano'),
('Latin', 'Timba'),
('Latin', 'Twoubadou'),
('Latin', 'Vallenato'),
('Latin', 'Zouk'),

-- Metal
('Metal', 'Heavy Metal'),
('Metal', 'Speed Metal'),
('Metal', 'Thrash Metal'),
('Metal', 'Power Metal'),
('Metal', 'Death Metal'),
('Metal', 'Black Metal'),
('Metal', 'Pagan Metal'),
('Metal', 'Viking Metal'),
('Metal', 'Folk Metal'),
('Metal', 'Symphonic Metal'),
('Metal', 'Gothic Metal'),
('Metal', 'Glam Metal'),
('Metal', 'Hair Metal'),
('Metal', 'Doom Metal'),
('Metal', 'Groove Metal'),
('Metal', 'Industrial Metal'),
('Metal', 'Modern Metal'),
('Metal', 'Neoclassical Metal'),
('Metal', 'New Wave Of British Heavy Metal'),
('Metal', 'Post Metal'),
('Metal', 'Progressive Metal'),
('Metal', 'Avantgarde Metal'),
('Metal', 'Sludge'),
('Metal', 'Djent'),
('Metal', 'Drone'),
('Metal', 'Kawaii Metal'),
('Metal', 'Pirate Metal'),
('Metal', 'Nu Metal'),
('Metal', 'Neue Deutsche Härte'),
('Metal', 'Math Metal'),
('Metal', 'Crossover'),
('Metal', 'Grindcore'),
('Metal', 'Hardcore'),
('Metal', 'Metalcore'),
('Metal', 'Deathcore'),
('Metal', 'Post Hardcore'),
('Metal', 'Mathcore'),

-- New Age
('New Age', 'Environmental'),
('New Age', 'Healing'),
('New Age', 'Meditation'),
('New Age', 'Nature'),
('New Age', 'Relaxation'),
('New Age', 'Travel'),

-- Opera
('Opera', 'Opera'),

-- Pop
('Pop', 'Adult Contemporary'),
('Pop', 'Arab Pop'),
('Pop', 'Baroque'),
('Pop', 'Britpop'),
('Pop', 'Bubblegum Pop'),
('Pop', 'Chamber Pop'),
('Pop', 'Chanson'),
('Pop', 'Christian Pop'),
('Pop', 'Classical Crossover'),
('Pop', 'Europop'),
('Pop', 'Austropop'),
('Pop', 'Balkan Pop'),
('Pop', 'French Pop'),
('Pop', 'Latin Pop'),
('Pop', 'Laïkó'),
('Pop', 'Nederpop'),
('Pop', 'Russian Pop'),
('Pop', 'Dance Pop'),
('Pop', 'Dream Pop'),
('Pop', 'Electro Pop'),
('Pop', 'Iranian Pop'),
('Pop', 'Jangle Pop'),
('Pop', 'Latin Ballad'),
('Pop', 'Levenslied'),
('Pop', 'Louisiana Swamp Pop'),
('Pop', 'Mexican Pop'),
('Pop', 'Motorpop'),
('Pop', 'New Romanticism'),
('Pop', 'Orchestral Pop'),
('Pop', 'Pop Rap'),
('Pop', 'Popera'),
('Pop', 'Pop/Rock'),
('Pop', 'Pop Punk'),
('Pop', 'Power Pop'),
('Pop', 'Psychedelic Pop'),
('Pop', 'Schlager'),
('Pop', 'Soft Rock'),
('Pop', 'Sophisti-Pop'),
('Pop', 'Space Age Pop'),
('Pop', 'Sunshine Pop'),
('Pop', 'Surf Pop'),
('Pop', 'Synthpop'),
('Pop', 'Teen Pop'),
('Pop', 'Traditional Pop Music'),
('Pop', 'Turkish Pop'),
('Pop', 'Vispop'),
('Pop', 'Wonky Pop'),

-- Post-Disco
('Post-Disco', 'Boogie'),
('Post-Disco', 'Dance-pop'),

-- Progressive
('Progressive', 'Progressive House / Trance'),
('Progressive', 'Disco House'),
('Progressive', 'Dream House'),
('Progressive', 'Space House'),
('Progressive', 'Japanese House'),
('Progressive', 'Bounce / Scouse House'),
('Progressive', 'Progressive Breaks'),
('Progressive', 'Progressive Drum & Bass'),
('Progressive', 'Progressive Techno'),

-- R&B/Soul
('R&B/Soul', 'Beach Music'),
('R&B/Soul', 'Contemporary R&B'),
('R&B/Soul', 'Disco'),
('R&B/Soul', 'Doo Wop'),
('R&B/Soul', 'Funk'),
('R&B/Soul', 'Modern Soul'),
('R&B/Soul', 'Motown'),
('R&B/Soul', 'Neo-Soul'),
('R&B/Soul', 'Northern Soul'),
('R&B/Soul', 'Psychedelic Soul'),
('R&B/Soul', 'Quiet Storm'),
('R&B/Soul', 'Soul'),
('R&B/Soul', 'Soul Blues'),
('R&B/Soul', 'Southern Soul'),

-- Reggae
('Reggae', '2-Tone'),
('Reggae', 'Dub'),
('Reggae', 'Roots Reggae'),
('Reggae', 'Reggae Fusion'),
('Reggae', 'Reggae en Español'),
('Reggae', 'Spanish Reggae'),
('Reggae', 'Reggae 110'),
('Reggae', 'Reggae Bultrón'),
('Reggae', 'Romantic Flow'),
('Reggae', 'Lovers Rock'),
('Reggae', 'Raggamuffin'),
('Reggae', 'Ragga'),
('Reggae', 'Dancehall'),
('Reggae', 'Ska'),
('Reggae', '2 Tone'),
('Reggae', 'Rocksteady'),
('Reggae', 'Reggae Dancehall'),

-- Rock
('Rock', 'Acid Rock'),
('Rock', 'Adult-Oriented Rock'),
('Rock', 'Afro Punk'),
('Rock', 'Adult Alternative'),
('Rock', 'Alternative Rock'),
('Rock', 'American Traditional Rock'),
('Rock', 'Anatolian Rock'),
('Rock', 'Arena Rock'),
('Rock', 'Art Rock'),
('Rock', 'Blues-Rock'),
('Rock', 'British Invasion'),
('Rock', 'Cock Rock'),
('Rock', 'Death Metal / Black Metal'),
('Rock', 'Doom Metal'),
('Rock', 'Glam Rock'),
('Rock', 'Gothic Metal'),
('Rock', 'Grind Core'),
('Rock', 'Hair Metal'),
('Rock', 'Hard Rock'),
('Rock', 'Math Metal'),
('Rock', 'Math Rock'),
('Rock', 'Metal'),
('Rock', 'Metal Core'),
('Rock', 'Noise Rock'),
('Rock', 'Jam Bands'),
('Rock', 'Post Punk'),
('Rock', 'Post Rock'),
('Rock', 'Prog-Rock/Art Rock'),
('Rock', 'Progressive Metal'),
('Rock', 'Psychedelic'),
('Rock', 'Rock & Roll'),
('Rock', 'Rockabilly'),
('Rock', 'Roots Rock'),
('Rock', 'Singer/Songwriter'),
('Rock', 'Southern Rock'),
('Rock', 'Spazzcore'),
('Rock', 'Stoner Metal'),
('Rock', 'Surf'),
('Rock', 'Technical Death Metal'),
('Rock', 'Tex-Mex'),
('Rock', 'Thrash Metal'),
('Rock', 'Time Lord Rock'),
('Rock', 'Trip-hop'),
('Rock', 'Yacht Rock'),

-- Singer/Songwriter
('Singer/Songwriter', 'Alternative Folk'),
('Singer/Songwriter', 'Contemporary Folk'),
('Singer/Songwriter', 'Contemporary Singer/Songwriter'),
('Singer/Songwriter', 'Indie Folk'),
('Singer/Songwriter', 'Folk-Rock'),
('Singer/Songwriter', 'Love Song'),
('Singer/Songwriter', 'New Acoustic'),
('Singer/Songwriter', 'Traditional Folk'),

-- Soundtrack
('Soundtrack', 'Foreign Cinema'),
('Soundtrack', 'Movie Soundtrack'),
('Soundtrack', 'Musicals'),
('Soundtrack', 'Original Score'),
('Soundtrack', 'Soundtrack'),
('Soundtrack', 'TV Soundtrack'),

-- Spoken Word
('Spoken Word', 'Spoken Word'),

-- Tex-Mex / Tejano
('Tex-Mex / Tejano', 'Chicano'),
('Tex-Mex / Tejano', 'Classic'),
('Tex-Mex / Tejano', 'Conjunto'),
('Tex-Mex / Tejano', 'Conjunto Progressive'),
('Tex-Mex / Tejano', 'New Mex'),
('Tex-Mex / Tejano', 'Tex-Mex'),

-- Vocal
('Vocal', 'A cappella'),
('Vocal', 'Barbershop'),
('Vocal', 'Cantique'),
('Vocal', 'Doo-wop'),
('Vocal', 'Gregorian Chant'),
('Vocal', 'Standards'),
('Vocal', 'Traditional Pop'),
('Vocal', 'Vocal Jazz'),
('Vocal', 'Vocal Pop'),
('Vocal', 'Yodel'),

-- World - Africa
('World', 'African Heavy Metal'),
('World', 'African Hip Hop'),
('World', 'Afro-Beat'),
('World', 'Afro-House'),
('World', 'Afro-Pop'),
('World', 'Apala'),
('World', 'Benga'),
('World', 'Bikutsi'),
('World', 'Bongo Flava'),
('World', 'Cape Jazz'),
('World', 'Chimurenga'),
('World', 'Coupé-Décalé'),
('World', 'Fuji Music'),
('World', 'Genge'),
('World', 'Gnawa'),
('World', 'Highlife'),
('World', 'Hiplife'),
('World', 'Isicathamiya'),
('World', 'Jit'),
('World', 'Jùjú'),
('World', 'Kapuka'),
('World', 'Kizomba'),
('World', 'Kuduro'),
('World', 'Kwaito'),
('World', 'Kwela'),
('World', 'Lingala'),
('World', 'Makossa'),
('World', 'Maloya'),
('World', 'Marrabenta'),
('World', 'Mbalax'),
('World', 'Mbaqanga'),
('World', 'Mbube'),
('World', 'Morna'),
('World', 'Museve'),
('World', 'Negro Spiritual'),
('World', 'Palm-Wine'),
('World', 'Raï'),
('World', 'Sakara'),
('World', 'Sega'),
('World', 'Seggae'),
('World', 'Semba'),
('World', 'Soukous'),
('World', 'Taarab'),
('World', 'Zouglou'),

-- World - Asia
('World', 'Anison'),
('World', 'Baithak Gana'),
('World', 'C-Pop'),
('World', 'CityPop'),
('World', 'Cantopop'),
('World', 'Enka'),
('World', 'Hong Kong English Pop'),
('World', 'Fann At-Tanbura'),
('World', 'Fijiri'),
('World', 'Khaliji'),
('World', 'Kayōkyoku'),
('World', 'Korean Pop'),
('World', 'Liwa'),
('World', 'Mandopop'),
('World', 'Onkyokei'),
('World', 'Taiwanese Pop'),
('World', 'T-Pop'),
('World', 'Sawt'),

-- World - Other
('World', 'Australia'),
('World', 'Cajun'),
('World', 'Calypso'),
('World', 'Caribbean'),
('World', 'Chutney'),
('World', 'Chutney Soca'),
('World', 'Compas'),
('World', 'Mambo'),
('World', 'Merengue'),
('World', 'Méringue'),
('World', 'Carnatic'),
('World', 'Celtic'),
('World', 'Celtic Folk'),
('World', 'Contemporary Celtic'),
('World', 'Dangdut'),
('World', 'Drinking Songs'),
('World', 'Drone'),
('World', 'Fado'),
('World', 'Laiko'),
('World', 'Entechno'),
('World', 'Rebetika'),
('World', 'Schlager'),
('World', 'France'),
('World', 'Hawaii'),
('World', 'Japan'),
('World', 'Klezmer'),
('World', 'Middle East'),
('World', 'North America'),
('World', 'Ode'),
('World', 'Piphat'),
('World', 'Polka'),
('World', 'Soca'),
('World', 'South Africa'),
('World', 'South America'),
('World', 'Baila'),
('World', 'Bhangra'),
('World', 'Bhojpuri'),
('World', 'Filmi'),
('World', 'Indian Pop'),
('World', 'Hindustani'),
('World', 'Indian Ghazal'),
('World', 'Lavani'),
('World', 'Luk Thung'),
('World', 'Luk Krung'),
('World', 'Manila Sound'),
('World', 'Morlam'),
('World', 'Pinoy Pop'),
('World', 'Pop Sunda'),
('World', 'Ragini'),
('World', 'Thai Pop'),
('World', 'Traditional Celtic'),
('World', 'Worldbeat'),
('World', 'Zydeco');

-- Create a view for easier genre browsing
CREATE OR REPLACE VIEW genre_summary AS
SELECT 
    genre,
    COUNT(*) as sub_genre_count,
    STRING_AGG(sub_genre, ', ' ORDER BY sub_genre) as sub_genres
FROM music_genres
GROUP BY genre
ORDER BY genre;

-- Query examples:
-- Get all genres: SELECT DISTINCT genre FROM music_genres ORDER BY genre;
-- Get sub-genres for a specific genre: SELECT sub_genre FROM music_genres WHERE genre = 'Rock' ORDER BY sub_genre;
-- Search sub-genres: SELECT * FROM music_genres WHERE sub_genre ILIKE '%jazz%';
-- Get genre summary: SELECT * FROM genre_summary;

COMMENT ON TABLE music_genres IS 'Comprehensive database of music genres and sub-genres';
COMMENT ON COLUMN music_genres.genre IS 'Main genre category';
COMMENT ON COLUMN music_genres.sub_genre IS 'Specific sub-genre or style within the main genre';
