-- Import Portfolio Data to PostgreSQL
-- Generated from p.csv
-- Database: Supabase (PostgreSQL)
-- Table: public.portfolio

-- Clear existing data (optional - remove comment if you want to start fresh)
-- TRUNCATE TABLE public.portfolio RESTART IDENTITY CASCADE;

-- Insert data from CSV
INSERT INTO public.portfolio (
  genre,
  song_title,
  album_title,
  singer,
  songwriter,
  composer,
  arranger,
  producer,
  mixing_engineer,
  mastering_engineer,
  publisher,
  aggregator,
  release_date_aggregator,
  youtube_link
) VALUES
-- 1. Sesungguhnya
('Pop', 'Sesungguhnya', 'Randomly Mixed', 
  ARRAY['Asyhilla']::text[], 
  ARRAY['Nano Suwarno', 'Steven Chan']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2024-04-25'::date, 
  'https://youtu.be/fajVFFTt-mQ'),

-- 2. Cinta Kita Berdua
('Pop', 'Cinta Kita Berdua', 'Randomly Mixed', 
  ARRAY['Asyhilla', 'Nannouz']::text[], 
  ARRAY['Nano Suwarno', 'Steven Chan']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2024-04-25'::date, 
  'https://youtu.be/mK9Rk3ya5ao'),

-- 3. Brotherly Bond
('Pop', 'Brotherly Bond', 'Randomly Mixed', 
  ARRAY['Nannouz', 'Adilisius']::text[], 
  ARRAY['Adi Subari', 'Nano Suwarno', 'Johanna Kakkuri']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2024-04-08'::date, 
  'https://youtu.be/bgUvT3Jiz3E?feature=shared'),

-- 4. Taqabalallahu Minna Wa Minkum
('Pop', 'Taqabalallahu Minna Wa Minkum', 'Songs of Faith', 
  ARRAY['TUTI', 'Dzaki', 'Andin']::text[], 
  ARRAY['Nano Suwarno']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2024-03-11'::date, 
  'https://youtu.be/eUtoI5qLttM?feature=shared'),

-- 5. Izinkan Aku Kembali
('Pop', 'Izinkan Aku Kembali', 'Songs of Faith', 
  ARRAY['WHO']::text[], 
  ARRAY['Nano Suwarno']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2024-03-11'::date, 
  'https://youtu.be/DemdcRYNkUM?feature=shared'),

-- 6. Kami Datang Menjelang
('Pop', 'Kami Datang Menjelang', 'Songs of Faith', 
  ARRAY['Nannouz', 'Adilisius', 'TUTI']::text[], 
  ARRAY['Adi Subari', 'Nano Suwarno']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2024-03-04'::date, 
  'https://youtu.be/fGZnsOFESJo?feature=shared'),

-- 7. Wahai Junjungan Kami
('Pop', 'Wahai Junjungan Kami', 'Songs of Faith', 
  ARRAY['Nannouz', 'WHO', 'Adilisius']::text[], 
  ARRAY['Adi Subari']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2024-02-26'::date, 
  'https://youtu.be/1Drr2LST9oQ?feature=shared'),

-- 8. Puasa Kita
('Pop', 'Puasa Kita', 'Songs of Faith', 
  ARRAY['Nannouz', 'Dzaki', 'Andin']::text[], 
  ARRAY['Nano Suwarno']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2024-02-21'::date, 
  'https://youtu.be/F-w8nOkGdfA'),

-- 9. أمي
('Pop', 'أمي', 'Songs of Faith', 
  ARRAY['Nannouz', 'SRI']::text[], 
  ARRAY['Dynta Nabila']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2024-01-05'::date, 
  'https://youtu.be/llqnp6XOytU?feature=shared'),

-- 10. Di Bait-Mu
('Pop', 'Di Bait-Mu', 'Songs of Faith', 
  ARRAY['Nannouz']::text[], 
  ARRAY['Nano Suwarno']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2023-12-06'::date, 
  'https://youtu.be/uKzb4buSIgM?feature=shared'),

-- 11. يا رسول الله
('Pop', 'يا رسول الله', 'Songs of Faith', 
  ARRAY['Nannouz']::text[], 
  ARRAY['Dynta Nabila', 'Nano Suwarno']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2023-10-26'::date, 
  'https://youtu.be/KLVbi5DlCTI?feature=shared'),

-- 12. Bapak
('Pop', 'Bapak', 'Songs of Faith', 
  ARRAY['Nannouz']::text[], 
  ARRAY['Nano Suwarno']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2023-10-18'::date, 
  'https://youtu.be/ETXx75ZkNmE?feature=shared'),

-- 13. Ku Tak Sebaik Itu
('Pop', 'Ku Tak Sebaik Itu', 'Lagu Untuk Ibu', 
  ARRAY['Indra']::text[], 
  ARRAY['Indra Gunawan']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2023-09-17'::date, 
  'https://youtu.be/GWgdzBXB-WI?feature=shared'),

-- 14. Karna Ku Sayang Kamu
('Pop', 'Karna Ku Sayang Kamu', 'Lagu Untuk Ibu', 
  ARRAY['WHO', 'The Kids']::text[], 
  ARRAY['Nano Suwarno', 'Sujarwo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2023-09-16'::date, 
  'https://youtu.be/HZZ1GY16J5c?feature=shared'),

-- 15. Ma mère
('Pop', 'Ma mère', 'Lagu Untuk Ibu', 
  ARRAY['Nannouz']::text[], 
  ARRAY['Lily Artha']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2023-09-16'::date, 
  'https://youtu.be/V5Gs97p17Uk?feature=shared'),

-- 16. Madre
('Pop', 'Madre', 'Lagu Untuk Ibu', 
  ARRAY['Nannouz']::text[], 
  ARRAY['Adi Subari', 'Re Mo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2023-09-16'::date, 
  'https://youtu.be/pw1Y5pr6AHg?feature=shared'),

-- 17. Untukmu Anakku
('Pop', 'Untukmu Anakku', 'Lagu Untuk Ibu', 
  ARRAY['Nannouz']::text[], 
  ARRAY['Nano Suwarno']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2023-09-16'::date, 
  'https://youtu.be/K3oohv1oLho?feature=shared'),

-- 18. IBU
('Pop', 'IBU', 'Lagu Untuk Ibu', 
  ARRAY['Nannouz']::text[], 
  ARRAY['Adi Subari']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2023-07-31'::date, 
  'https://youtu.be/2fk-WqSR1Rc?feature=shared'),

-- 19. Minor
('Pop', 'Minor', 'Senandika', 
  ARRAY['Hendy Kris', 'Ovi']::text[], 
  ARRAY['Hendy Kris']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2023-07-23'::date, 
  'https://youtu.be/PDI5Bc0GSX0?feature=shared'),

-- 20. Sudah
('Pop', 'Sudah', 'Senandika', 
  ARRAY['Hendy Kris', 'Ovi']::text[], 
  ARRAY['Hendy Kris']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2023-07-23'::date, 
  'https://youtu.be/JEwG3XVs4mc?feature=shared'),

-- 21. Diam
('Pop', 'Diam', 'Senandika', 
  ARRAY['Hendy Kris', 'Ovi']::text[], 
  ARRAY['Odik', 'Hendy Kris']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2023-07-23'::date, 
  'https://youtu.be/Z8DuWIEXm30?feature=shared'),

-- 22. It's A Long Road
('Pop', 'It''s A Long Road', 'Randomly Mixed', 
  ARRAY['Nannouz']::text[], 
  ARRAY['Nano Suwarno']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2023-09-17'::date, 
  'https://youtu.be/FcBB4GiCBL4?feature=shared'),

-- 23. On The Road Again
('Pop', 'On The Road Again', 'Randomly Mixed', 
  NULL, 
  ARRAY['Johanna Kakkuri', 'Adi Subari']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2023-11-10'::date, 
  'https://youtu.be/BkoUw7U-rBE?feature=shared'),

-- 24. Nyt Ollan "On The Road Again"
('Pop', 'Nyt Ollan "On The Road Again"', 'Randomly Mixed', 
  ARRAY['Adilisius']::text[], 
  ARRAY['Johanna Kakkuri', 'Adi Subari']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2023-12-07'::date, 
  'https://youtu.be/_Rq4j6xGFsU?feature=shared'),

-- 25. Probably
('Pop', 'Probably', 'Probably', 
  ARRAY['Felicia Angelica']::text[], 
  ARRAY['Felicia Angelica']::text[], 
  ARRAY['Felicia Angelica', 'Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2023-12-19'::date, 
  'https://youtu.be/i7lUuLC4sKY?feature=shared'),

-- 26. Menjadi Bintang
('Pop', 'Menjadi Bintang', 'Menjadi Bintang', 
  ARRAY['Felicia Angelica']::text[], 
  ARRAY['Felicia Angelica']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2023-12-24'::date, 
  'https://youtu.be/8zs6W5LhB_o?feature=shared'),

-- 27. Anaking
('Pop', 'Anaking', 'Nusantara', 
  ARRAY['Nannouz']::text[], 
  ARRAY['Nano Suwarno']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2023-12-07'::date, 
  'https://youtu.be/UlsrDF71t8A?feature=shared'),

-- 28. Luka Tak Terobati
('Pop Ballad', 'Luka Tak Terobati', 'Luka Tak Terobati', 
  ARRAY['Deddy Chen']::text[], 
  ARRAY['Maharsyalfath', 'Deddy Chen']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Hery Alesis']::text[], 
  ARRAY['Hery Alesis']::text[], 
  ARRAY['Deddy Chen']::text[], 
  ARRAY['TuneCore']::text[], 
  '2024-02-29'::date, 
  'https://youtu.be/ukM7D3FL2og?feature=shared'),

-- 29. Jangan Halangi Pintu
('Pop Ballad', 'Jangan Halangi Pintu', 'Randomly Mixed', 
  ARRAY['Indra Rawi']::text[], 
  ARRAY['Indra Rawi']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2024-04-09'::date, 
  'https://youtu.be/4AbohCUOBB8?feature=shared'),

-- 30. Hilang di Awan
('Pop/RnB', 'Hilang di Awan', 'Senandika', 
  ARRAY['Hendy Kris', 'Ovi']::text[], 
  ARRAY['Hendy Kris']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2023-07-23'::date, 
  'https://youtu.be/XD23rkG5gVg?feature=shared'),

-- 31. Life's Only Once (Duet)
('Pop-Jazz', 'Life''s Only Once (Duet)', 'Randomly Mixed', 
  ARRAY['Nannouz', 'Adilisius']::text[], 
  ARRAY['Nano Suwarno', 'Maharsyalfath']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2024-04-22'::date, 
  'https://youtu.be/lexa1UZRypU?feature=shared'),

-- 32. Life's Only Once
('Pop-Jazz', 'Life''s Only Once', 'Lagu Untuk Ibu', 
  ARRAY['Nannouz']::text[], 
  ARRAY['Adi Subari', 'Maharsyalfath']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2023-07-31'::date, 
  'https://youtu.be/zmRF3h6EW2Q?feature=shared'),

-- 33. Strange
('Pop-Jazz', 'Strange', 'Strange', 
  ARRAY['Felicia Angelica']::text[], 
  ARRAY['Felicia Angelica']::text[], 
  ARRAY['Felicia Angelica', 'Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2023-12-19'::date, 
  'https://youtu.be/4-30iYx31LU?feature=shared'),

-- 34. Senandika
('Pop Indie/Folk', 'Senandika', 'Senandika', 
  ARRAY['Hendy Kris']::text[], 
  ARRAY['Demas Azzaq', 'Hendy Kris']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Ade', 'Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2023-07-23'::date, 
  'https://youtu.be/5Vc7G0ANJNg?feature=shared'),

-- 35. Mengapa
('Pop Indie/Folk', 'Mengapa', 'Senandika', 
  ARRAY['Hendy Kris', 'Ovi']::text[], 
  ARRAY['Hendy Kris']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2023-07-23'::date, 
  'https://youtu.be/qVEGe87ZuvQ?feature=shared'),

-- 36. Missen
('Pop Orchestra', 'Missen', 'Senandika', 
  ARRAY['Hendy Kris']::text[], 
  ARRAY['Hendy Kris']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2023-07-23'::date, 
  'https://youtu.be/tiLhdF6BQ1k?feature=shared'),

-- 37. Kau Katakan
('Pop-Rock', 'Kau Katakan', 'Kau Katakan', 
  ARRAY['Redi Story']::text[], 
  ARRAY['Redi Story']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2024-02-26'::date, 
  'https://youtu.be/9XaTqRUUIuc?feature=shared'),

-- 38. Tarian Capung
('Pop Anak-Anak', 'Tarian Capung', 'Tarian Capung', 
  ARRAY['Dynta Nabila']::text[], 
  ARRAY['Dynta Nabila']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  NULL, 
  NULL, 
  NULL, 
  'https://youtu.be/EsCcz17BFAk?feature=shared'),

-- 50. Lights In Your Eyes
('Jazz', 'Lights In Your Eyes', 'Randomly Mixed', 
  ARRAY['Nannouz']::text[], 
  ARRAY['Nano Suwarno']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2024-04-08'::date, 
  'https://youtu.be/H-_3_uVuSgc?feature=shared'),

-- 51. Salah Sangka Salah Duga
('Jazz', 'Salah Sangka Salah Duga', 'Randomly Mixed', 
  ARRAY['Nannouz']::text[], 
  ARRAY['Nano Suwarno']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2024-04-08'::date, 
  'https://youtu.be/xIeRcV2cQuM?feature=shared'),

-- 52. La luce lunare
('Jazz', 'La luce lunare', 'Randomly Mixed', 
  ARRAY['Nannouz']::text[], 
  ARRAY['Nano Suwarno']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2024-01-08'::date, 
  'https://youtu.be/h-bgGZ0xezk?feature=shared'),

-- 53. Moonlight
('Jazz', 'Moonlight', 'Randomly Mixed', 
  ARRAY['Nannouz']::text[], 
  ARRAY['Dynta Nabila', 'Nano Suwarno']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2023-12-06'::date, 
  'https://youtu.be/JKg0WgZONHw?feature=shared'),

-- 54. Akankah Kita
('Jazz', 'Akankah Kita', 'Senandika', 
  ARRAY['Hendy Kris', 'Ovi']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2023-07-23'::date, 
  'https://youtu.be/MHtazxL9TuI?feature=shared'),

-- 55. Terpaut Rindu
('Bossa Nova/Jazz', 'Terpaut Rindu', 'Terpaut Rindu', 
  ARRAY['Rusli Zainudin']::text[], 
  ARRAY['Rusli Zainudin']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  NULL, 
  'https://youtu.be/OoiI577HOJQ?feature=shared'),

-- 57. Rasa Cinta
('EDM', 'Rasa Cinta', 'Rasa Cinta', 
  ARRAY['Bamus']::text[], 
  ARRAY['Bambang P']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2023-12-18'::date, 
  'https://youtu.be/P8pHQbetCnU?feature=shared'),

-- 58. Tunggu Aku Kembali
('EDM', 'Tunggu Aku Kembali', 'Tunggu Aku Kembali', 
  ARRAY['Bamus']::text[], 
  ARRAY['Bambang P']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2024-01-08'::date, 
  'https://youtu.be/RtRiUHoRoHM?feature=shared'),

-- 59. Bandung, I Love You Forever
('Dangdut', 'Bandung, I Love You Forever', 'Lagu Untuk Ibu', 
  ARRAY['Nannouz']::text[], 
  ARRAY['Adi Subari']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2023-09-16'::date, 
  'https://youtu.be/58SgitLCAeY?feature=shared'),

-- 60. Jangji Pasini
('Dangdut', 'Jangji Pasini', 'Lagu Untuk Ibu', 
  ARRAY['Nannouz', 'SRI']::text[], 
  ARRAY['Adi Subari']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Flemmo Music Global']::text[], 
  ARRAY['Amuse']::text[], 
  '2023-09-16'::date, 
  'https://youtu.be/2xNIjmOdsbA?feature=shared'),

-- 61. Lemu
('Dangdut Ambyar', 'Lemu', 'Lemu', 
  ARRAY['Maliq Abdullah']::text[], 
  ARRAY['Maliq Abdullah']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  ARRAY['Alfath Flemmo']::text[], 
  NULL, 
  NULL, 
  '2023-07-22'::date, 
  'https://youtu.be/Tke8mrZkCjQ?feature=shared');

-- Note: Records 39-49 and 56, 62-68 are marked as "Belum Rilis" (Not Yet Released) in CSV
-- and have been omitted from this import. Add them when they are released.

-- Verify import
SELECT COUNT(*) as total_imported FROM public.portfolio;

-- View sample records
SELECT 
  id,
  song_title,
  array_to_string(singer, ', ') as singers,
  genre,
  release_date_aggregator
FROM public.portfolio
ORDER BY release_date_aggregator DESC NULLS LAST
LIMIT 10;
