"use client";

import { FormEvent, useMemo, useState } from "react";
import { Loader2, Trash2, X } from "lucide-react";
import { WORK_TYPES, type PortfolioItem, type WorkType } from "./types";

const EMPTY={genre:"",song_title:"",album_title:"",singer:"",arranger:"",producer:"",mixing_engineer:"",mastering_engineer:"",songwriter:"",composer:"",publisher:"",aggregator:"",release_date_aggregator:"",spotify_link:"",youtube_link:"",apple_music_link:"",artwork_link:"",priority_order:"",work_type:["release"] as WorkType[],client_brief:"",challenge:"",arrangement_solution:"",before_url:"",after_url:"",turnaround_days:"",revision_count:"",deliverables:"",testimonial_quote:"",testimonial_name:""};
const join=(value:string[]|null|undefined)=>(value||[]).join(", ");
const split=(value:string)=>value.split(",").map(v=>v.trim()).filter(Boolean);

export default function PortfolioAdminEditor({item,onClose,onSaved}:{item:PortfolioItem|null;onClose:()=>void;onSaved:()=>void}){
  const initial=useMemo(()=>item?{...EMPTY,...item,singer:join(item.singer),arranger:join(item.arranger),producer:join(item.producer),mixing_engineer:join(item.mixing_engineer),mastering_engineer:join(item.mastering_engineer),songwriter:join(item.songwriter),composer:join(item.composer),publisher:join(item.publisher),aggregator:join(item.aggregator),deliverables:join(item.deliverables),album_title:item.album_title||"",release_date_aggregator:item.release_date_aggregator||"",spotify_link:item.spotify_link||"",youtube_link:item.youtube_link||"",apple_music_link:item.apple_music_link||"",artwork_link:item.artwork_link||"",priority_order:item.priority_order?.toString()||"",client_brief:item.client_brief||"",challenge:item.challenge||"",arrangement_solution:item.arrangement_solution||"",before_url:item.before_url||"",after_url:item.after_url||"",turnaround_days:item.turnaround_days?.toString()||"",revision_count:item.revision_count?.toString()||"",testimonial_quote:item.testimonial_quote||"",testimonial_name:item.testimonial_name||""}:EMPTY,[item]);
  const [form,setForm]=useState(initial); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [confirmDelete,setConfirmDelete]=useState(false);
  const set=(key:string,value:unknown)=>setForm(current=>({...current,[key]:value}));
  async function save(event:FormEvent){event.preventDefault();setBusy(true);setMessage(""); const nullable=(v:string)=>v.trim()||null; const payload={...(item?{id:item.id}:{}),genre:form.genre,song_title:form.song_title,album_title:nullable(form.album_title),singer:split(form.singer),arranger:split(form.arranger),producer:split(form.producer),mixing_engineer:split(form.mixing_engineer),mastering_engineer:split(form.mastering_engineer),songwriter:split(form.songwriter),composer:split(form.composer),publisher:split(form.publisher),aggregator:split(form.aggregator),release_date_aggregator:nullable(form.release_date_aggregator),spotify_link:nullable(form.spotify_link),youtube_link:nullable(form.youtube_link),apple_music_link:nullable(form.apple_music_link),artwork_link:nullable(form.artwork_link),priority_order:form.priority_order?Number(form.priority_order):null,is_featured:item?.is_featured||false,work_type:form.work_type,client_brief:nullable(form.client_brief),challenge:nullable(form.challenge),arrangement_solution:nullable(form.arrangement_solution),before_url:nullable(form.before_url),after_url:nullable(form.after_url),turnaround_days:form.turnaround_days?Number(form.turnaround_days):null,revision_count:form.revision_count!==""?Number(form.revision_count):null,deliverables:split(form.deliverables),testimonial_quote:nullable(form.testimonial_quote),testimonial_name:nullable(form.testimonial_name)}; const response=await fetch("/api/portfolio",{method:item?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}); const body=await response.json().catch(()=>({}));setBusy(false);if(!response.ok){setMessage(typeof body.error==="string"?body.error:"Could not save portfolio item.");return;}onSaved();}
  async function remove(){if(!item)return;setBusy(true);const response=await fetch(`/api/portfolio?id=${item.id}`,{method:"DELETE"});setBusy(false);if(!response.ok){setMessage("Could not delete portfolio item.");return;}onSaved();}
  const field="rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm outline-none focus:border-violet-500 dark:border-white/15 dark:bg-black";
  return <div className="fixed inset-0 z-[100] overflow-y-auto bg-black/70 p-4 backdrop-blur-sm"><div role="dialog" aria-modal="true" className="mx-auto my-6 max-w-4xl rounded-3xl bg-white p-6 text-slate-950 shadow-2xl dark:bg-zinc-950 dark:text-white"><div className="flex items-center justify-between"><h2 className="text-2xl font-bold">{item?"Edit portfolio case":"Add portfolio case"}</h2><button onClick={onClose} aria-label="Close editor" className="rounded-full p-2 hover:bg-slate-100 dark:hover:bg-white/10"><X/></button></div><form onSubmit={save} className="mt-6 grid gap-4 sm:grid-cols-2">
    {[['song_title','Song title'],['album_title','Album title'],['genre','Genre'],['singer','Artist / singer'],['arranger','Arranger credits'],['producer','Producer credits'],['mixing_engineer','Mixing credits'],['mastering_engineer','Mastering credits'],['songwriter','Songwriter credits'],['composer','Composer credits'],['publisher','Publisher'],['aggregator','Aggregator'],['release_date_aggregator','Release date'],['artwork_link','Artwork URL'],['spotify_link','Spotify URL'],['youtube_link','YouTube URL'],['apple_music_link','Apple Music URL'],['priority_order','Priority order'],['turnaround_days','Turnaround days'],['revision_count','Revision rounds'],['before_url','Before audio URL'],['after_url','After audio URL'],['testimonial_name','Testimonial name']].map(([key,label])=><label key={key} className="grid gap-1.5 text-sm font-medium">{label}<input required={key==='song_title'||key==='genre'} type={key==='release_date_aggregator'?'date':key.includes('days')||key.includes('revision')||key==='priority_order'?'number':'text'} className={field} value={String((form as Record<string,unknown>)[key]??"")} onChange={e=>set(key,e.target.value)}/></label>)}
    <fieldset className="sm:col-span-2"><legend className="text-sm font-semibold">Explicit work type</legend><div className="mt-2 flex flex-wrap gap-2">{WORK_TYPES.map(type=><label key={type} className="inline-flex items-center gap-2 rounded-full border border-slate-300 px-3 py-2 text-sm capitalize dark:border-white/15"><input type="checkbox" checked={form.work_type.includes(type)} onChange={e=>set('work_type',e.target.checked?[...form.work_type,type]:form.work_type.filter(value=>value!==type))}/>{type}</label>)}</div></fieldset>
    {[['client_brief','Client brief'],['challenge','Arrangement problem'],['arrangement_solution','Arrangement solution'],['deliverables','Deliverables (comma-separated)'],['testimonial_quote','Project testimonial']].map(([key,label])=><label key={key} className="grid gap-1.5 text-sm font-medium sm:col-span-2">{label}<textarea rows={3} className={field} value={String((form as Record<string,unknown>)[key]??"")} onChange={e=>set(key,e.target.value)}/></label>)}
    {message&&<p role="status" className="text-sm text-rose-600 sm:col-span-2">{message}</p>}<div className="flex flex-wrap justify-between gap-3 sm:col-span-2"><div>{item&&(confirmDelete?<button type="button" disabled={busy} onClick={()=>void remove()} className="inline-flex items-center gap-2 rounded-xl bg-rose-600 px-4 py-2.5 font-semibold text-white"><Trash2 className="h-4 w-4"/> Confirm delete</button>:<button type="button" onClick={()=>setConfirmDelete(true)} className="inline-flex items-center gap-2 rounded-xl border border-rose-300 px-4 py-2.5 font-semibold text-rose-700 dark:border-rose-800 dark:text-rose-300"><Trash2 className="h-4 w-4"/> Delete</button>)}</div><button disabled={busy||form.work_type.length===0} className="inline-flex items-center gap-2 rounded-xl bg-violet-600 px-5 py-2.5 font-semibold text-white disabled:opacity-50">{busy&&<Loader2 className="h-4 w-4 animate-spin"/>}{busy?"Saving…":"Save portfolio case"}</button></div>
  </form></div></div>;
}
